from enum import Enum

class AppCode(str, Enum):
    SUCCESS = "SUCCESS"
    MOVIE_ADDED = "MOVIE_ADDED"
    MOVIE_NOT_ADDED = "MOVIE_NOT_ADDED"
    MOVIE_FOUND = "MOVIE_FOUND"
    MOVIE_NOT_FOUND = "ERR_MOVIE_NOT_FOUND"
    MOVIE_EMPTY = "ERR_MOVIE_EMPTY"
    MOVIE_DUPLICATED = "ERR_MOVIE_DUPLICATED"
    MOVIE_UPDATED = "MOVIE_UPDATED"
    MOVIE_NOT_UPDATED = "MOVIE_NOT_UPDATED"
    MOVIE_DELETED = "MOVIE_DELETED"
    MOVIE_NOT_DELETED = "MOVIE_NOT_DELETED"
